### PR TITLE
recover CI/CD files

### PR DESCRIPTION
**Pull request by lukmay**

### CODE REVIEW

**Comment by RudiThoeni** [comment]
@lukmay if you add to wcs-manifest.json
repositoryUrl
i think deployment should work

**Comment by lukmay** [comment]
Thank you, @RudiThoeni :) added the repositoryUrl.
Now I get an error where it is not written what is missing.
I will investigate what's still missing.

**Comment by RudiThoeni** [comment]
@lukmay thx,  alright i merged and the Webcomponent is online https://webcomponents.opendatahub.testingmachine.eu/webcomponent/near-parking
The only thing is that he has set a default value for the parameter that is nto working
Can you investigate here and add another PR ?

**Comment by lukmay** [comment]
@RudiThoeni sure already on it.

**Comment by RudiThoeni** [comment]
@lukmay ok i fixed now it is working

**Pull request merged**
